name: compile

on:
  push:
    branches: [ master, actiontest ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: deps
      run: |
        sudo apt-get install -y libcfitsio-dev
        sudo pip3 install numpy fitsio
    - name: make
      run: |
        make
        make py
        make extra
        make test
